spring.application.name=listing-service

server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/estatehub}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:estatehub}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:estatehub}
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
spring.kafka.consumer.group-id=listing-service-media-sync
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

app.jwt.secret=${APP_JWT_SECRET:Z8rN4yXJvP6KQe3H9sWc2F5M7BfTqLkRjA6mU0aE1dSxYJpPzCwVnH}

logging.level.root=INFO
logging.level.com.rlnkoo.listingservice=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.apache.kafka.clients=WARN
logging.level.org.apache.kafka.common=WARN
logging.level.org.springframework.kafka=INFO