spring.application.name=search-service

server.port=8084

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=search-service-listing-events
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.elasticsearch.uris=http://localhost:9200

app.jwt.secret=Z8rN4yXJvP6KQe3H9sWc2F5M7BfTqLkRjA6mU0aE1dSxYJpPzCwVnH

app.search.index-name=listings
app.search.default-page-size=20
app.search.max-page-size=100

management.endpoints.web.exposure.include=health,info

logging.level.root=INFO
logging.level.com.rlnkoo.searchservice=DEBUG
logging.level.org.apache.kafka=WARN
logging.level.org.apache.kafka.clients=WARN
logging.level.org.apache.kafka.common=WARN
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.data.elasticsearch=INFO
logging.level.co.elastic.clients=INFO